global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

alerting:
  alertmanagers:
  - static_configs:
    - targets: ['alertmanager:9093']

rule_files:
  - /usr/local/prometheus/rules/*.rules

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
 
  - job_name: 'node-exporter'
    scrape_interval: 8s
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'cloudprober'
    scrape_interval: 10s
    static_configs:
      - targets: ['cloudprober:9313']
  
  - job_name: 'mysql-exporter'
    scrape_interval: 8s
    static_configs:
      - targets: ['mysql-exporter:9104']
      
  - job_name: 'springboot_prometheus'
    scrape_interval: 5s
    metrics_path: '/actuator/prometheus'
    static_configs:
    #这里的地址为本机ip
      - targets: ['192.168.32.42:8090']
